# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turengv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tureng import TurEng


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 173)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 22))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(370, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 431, 121))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 10, 51, 21))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton.clicked.connect(self.ttrr)
        self.pushButton_2.clicked.connect(self.changeL)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def changeL(self):
        print(self.pushButton_2.text())
        if self.pushButton_2.text() =="ENG/TR":
            self.pushButton_2.setText("TR/ENG")
        elif self.pushButton_2.text() =="TR/ENG":
            self.pushButton_2.setText("ENG/TR")
    def ttrr(self):
        tureng = TurEng()
        word = self.lineEdit.text()

        if self.pushButton_2.text()=="TR/ENG":
            try:
                print("x")
                result = tureng.translate(f"{word.lower()}")
                if len(result.all_en_translation_str)==0:
                    self.listWidget.clear()
                    self.listWidget.addItem("Kelime Bulunamadı...")
                    try:
                        self.listWidget.addItems(result.suggestions)
                    except:
                        self.listWidget.addItem("Tavsiye Bulunamadı...")

                else:
                    print("x")
                    self.listWidget.clear()
                    self.listWidget.addItems(result.all_en_translation_str)

            except:
                self.listWidget.clear()
                self.listWidget.addItem("Kelime Bulunamadı...")
                try:
                    self.listWidget.addItems(result.suggestions)
                except:
                    self.listWidget.addItem("Tavsiye Bulunamadı...")

        elif self.pushButton_2.text()=="ENG/TR":
            if word == "lülü":
                word = "love"
            if word == "fati":
                word = "devastated"
            try:

                result = tureng.translate(f"{word.lower()}")
                if len(result.all_tr_translation_str)==0:
                    self.listWidget.clear()
                    self.listWidget.addItem("Kelime Bulunamadı...")
                    try:
                        self.listWidget.addItems(result.suggestions)
                    except:
                        self.listWidget.addItem("Tavsiye Bulunamadı...")
                else:
                    self.listWidget.clear()
                    self.listWidget.clear()
                    self.listWidget.addItems(result.all_tr_translation_str)
            except:

                self.listWidget.clear()
                self.listWidget.addItem("Kelime Bulunamadı...")
                try:
                    self.listWidget.addItems(result.suggestions)
                except:
                    self.listWidget.addItem("Tavsiye Bulunamadı...")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Çevir"))
        self.pushButton_2.setText(_translate("Form", "TR/ENG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
