# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turengv3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui  import *
from PyQt5.QtWidgets import *
from tureng import TurEng
import time
from pyperclip import waitForNewPaste,paste
from deep_translator import GoogleTranslator
import threading,sys,os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 172)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 22))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(370, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 431, 121))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 10, 51, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 70, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(450, 10, 111, 21))
        self.checkBox.setObjectName("otomatikAlgılama")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(450, 30, 101, 21))
        self.checkBox_2.setObjectName("CümleÇeviri")

        self.checkBox.clicked.connect(self.decision2)

        self.pushButton.clicked.connect(self.ttrr)
        self.pushButton_2.clicked.connect(self.changeL)
        self.pushButton_3.clicked.connect(self.save)



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def save(self):
        try:
            text=self.lineEdit.text()
            meaning=[]
            for i in range(1,5):
                meaning.append(self.listWidget.item(i).text())
            print(meaning)

            with open("veriler.txt", "r+", encoding="utf-8") as file:
                file.write(f"{text}={meaning}")
                file.write("\n")
            os.system("python notlar.py")
        except:
            os.system("python notlar.py")

    def copy_pasteD(self,d):
        self.lineEdit.setText(f"{d}")
        self.ttrr()
        if self.checkBox.isChecked():
            time.sleep(2)
            self.decision()

    def decision2(self):
        import deneme
        p1 = threading.Thread(target=deneme.copy_pasteDec())
        p1.start()
        p1.join()

    def decision(self):
        import deneme,threading
        p1 = threading.Thread(target=deneme.copy_pasteDec())
        p1.start()
        p1.join()
        with open("copy_paste.txt", "r+", encoding="utf-8") as file:
            word=file.readline()

        with open("copy_paste.txt", "w", encoding="utf-8") as file:
            w=""
        self.lineEdit.setText(f"{word}")
        self.ttrr()



    def changeL(self):
        print(self.pushButton_2.text())
        if self.pushButton_2.text() =="ENG/TR":
            self.pushButton_2.setText("TR/ENG")
        elif self.pushButton_2.text() =="TR/ENG":
            self.pushButton_2.setText("ENG/TR")
    def autoDetection(self,currentText):

        word=currentText
        word=word.lower()
        self.lineEdit.setText(f"{word}")


        if self.pushButton_2.text()=="TR/ENG":
            try:
                result = tureng.translate(f"{word.lower()}")
                if len(result.all_en_translation_str)==0:
                    self.listWidget.clear()
                    self.listWidget.addItem("Kelime Bulunamadı...")
                    try:
                        self.listWidget.addItems(result.suggestions)
                    except:
                        self.listWidget.addItem("Tavsiye Bulunamadı...")
                else:

                    self.listWidget.clear()
                    self.listWidget.addItems(result.all_en_translation_str)

            except:
                self.listWidget.clear()
                self.listWidget.addItem("Kelime Bulunamadı...")
                try:
                    self.listWidget.addItems(result.suggestions)
                except:
                    self.listWidget.addItem("Tavsiye Bulunamadı...")

        elif self.pushButton_2.text()=="ENG/TR":
            if word == "lülü":
                word = "love"
            if word == "fati":
                word = "devastated"
            try:

                result = tureng.translate(f"{word.lower()}")
                if len(result.all_tr_translation_str)==0:
                    self.listWidget.clear()
                    self.listWidget.addItem("Kelime Bulunamadı...")
                    try:
                        self.listWidget.addItems(result.suggestions)
                    except:
                        self.listWidget.addItem("Tavsiye Bulunamadı...")
                else:
                    self.listWidget.clear()
                    self.listWidget.clear()
                    self.listWidget.addItems(result.all_tr_translation_str)
            except:

                self.listWidget.clear()
                self.listWidget.addItem("Kelime Bulunamadı...")
                try:
                    self.listWidget.addItems(result.suggestions)
                except:
                    self.listWidget.addItem("Tavsiye Bulunamadı...")

    def ttrr(self):
        if self.checkBox_2.isChecked():
            if self.pushButton_2.text() == "TR/ENG":
                try:
                    self.listWidget.clear()
                    sentence = self.lineEdit.text()
                    çeviri = GoogleTranslator(source='tr', target='en').translate(sentence)
                    self.listWidget.addItem(çeviri)
                except:
                    self.listWidget.clear()
                    self.listWidget.addItem("Cümle Çevrilemiyor...")

            elif self.pushButton_2.text() == "ENG/TR":
                try:
                    self.listWidget.clear()
                    sentence = self.lineEdit.text()
                    çeviri = GoogleTranslator(source='en', target='tr').translate(sentence)
                    self.listWidget.addItem(çeviri)
                except:
                    self.listWidget.clear()
                    self.listWidget.addItem("Cümle Çevrilemiyor...")

        elif not self.checkBox_2.isChecked():
            tureng = TurEng()
            word = self.lineEdit.text()


            if self.pushButton_2.text()=="TR/ENG":
                try:
                    result = tureng.translate(f"{word.lower()}")
                    if len(result.all_en_translation_str)==0:
                        self.listWidget.clear()
                        self.listWidget.addItem("Kelime Bulunamadı...")
                        try:
                            self.listWidget.addItems(result.suggestions)
                        except:
                            self.listWidget.addItem("Tavsiye Bulunamadı...")

                    else:
                        print("x")
                        self.listWidget.clear()
                        self.listWidget.addItems(result.all_en_translation_str)

                except:
                    self.listWidget.clear()
                    self.listWidget.addItem("Kelime Bulunamadı...")
                    try:
                        self.listWidget.addItems(result.suggestions)
                    except:
                        self.listWidget.addItem("Tavsiye Bulunamadı...")

            elif self.pushButton_2.text()=="ENG/TR":
                if word == "lülü":
                    word = "love"
                if word == "fati":
                    word = "devastated"
                try:

                    result = tureng.translate(f"{word.lower()}")
                    if len(result.all_tr_translation_str)==0:
                        self.listWidget.clear()
                        self.listWidget.addItem("Kelime Bulunamadı...")
                        try:
                            self.listWidget.addItems(result.suggestions)
                        except:
                            self.listWidget.addItem("Tavsiye Bulunamadı...")
                    else:
                        self.listWidget.clear()
                        self.listWidget.clear()
                        self.listWidget.addItems(result.all_tr_translation_str)
                except:

                    self.listWidget.clear()
                    self.listWidget.addItem("Kelime Bulunamadı...")
                    try:
                        self.listWidget.addItems(result.suggestions)
                    except:
                        self.listWidget.addItem("Tavsiye Bulunamadı...")
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Çevir"))
        self.pushButton_2.setText(_translate("Form", "TR/ENG"))
        self.pushButton_3.setText(_translate("Form", "KAYDET"))
        self.checkBox.setText(_translate("Form", "Otomatik Algılama"))
        self.checkBox_2.setText(_translate("Form", "Cümle Çevir"))


class Ui_Form2(object):
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(341, 392)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

         #self.listWidget.addItem(f"{sentence}==>{meaning}")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)

    Form.show()
    sys.exit(app.exec_())
